### ISSUE TITLE
Issue with the contact.html file

### ISSUE THREAD

**Issue by Boby900** [Boby900/Basic-HTML#1]
1. I am unable to put the **Name** and **Email** inputs inside the textarea(message-box).

1. If you can fix it it will be so helpful

![Screenshot (23)](https://user-images.githubusercontent.com/111265239/211181794-ec542291-178f-4ca5-a703-e017894be103.png)

**Comment by Halim-Shams** [comment]
Hi, I can help you with, please explain a little clear. If your suggestion is to put the "Name" and "Email" inputs inside the "textarea" input, that's not a good idea at all.

**Comment by shyamtawli** [comment]
Hello @Boby900 please explain clearly what do you want to resolve?

**Comment by alok-38** [comment]
Can I be of any help?

**Comment by Boby900** [comment]
I want the name and email section to be inside the `text-area tag` box, can you help with that.
If you wants to so you can expand the size of the `text-area`

**Comment by alok-38** [comment]
Would you like to embed the name and email input elements inside textarea?

**Comment by Boby900** [comment]
yes

**Comment by alok-38** [comment]
The closest that I could get was try to understand [this](https://stackoverflow.com/questions/1638599/how-can-i-embed-a-textarea-inside-of-another-textarea-in-html).
I tried reading the entire post but I am having difficulty with it.

**Comment by Boby900** [comment]
Ok, I'll check it out.
